pipeline {
    agent any
	
    stages {
        stage('Build Application') {
	    tools {
        maven 'Maven'
            }
            steps {
		 
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
	    
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        
        
    }
}
