pipeline {
    agent any
	
    stages {
        stage('Build Application') {
	    def mvnHome = tool name: 'Maven', type: 'maven'
	    def mvnCMD = "${mvnHome}/bin/mvn"
            steps {
		 sh '{mvnHome}/bin/mvn -f java-tomcat-sample/pom.xml clean package'
	    }
	    
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'deploy_appl_stag'

            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'Deploy_Appln_Prod'
            }
        }
    }
}
